version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.local
    volumes:
      - ./:/go/src/app
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://manager:password@db:5432/awscdk-go-template?sslmode=disable
      - ADDR=:8080

  db:
    image: postgres:11.8
    ports:
      - "6032:5432"
    environment:
      - POSTGRES_USER=manager
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=awscdk-go-template
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    driver: local
